In [46]:
import scipy
from scipy.linalg import lu 
import numpy as np
import pprint
from numpy import linalg as LA


In [47]:
def LU_factorization_lib(A):
    P, L, U = lu(A)
    return P, L, U

In [48]:
LU_factorization_lib(A)

(array([[1., 0., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 0., 1.]]),
 array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  1.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  1., ...,  0.,  0.,  0.],
        ...,
        [ 0.,  0.,  0., ...,  1.,  0.,  0.],
        [ 0.,  0.,  0., ..., -0.,  1.,  0.],
        [ 0.,  0.,  0., ..., -0., -0.,  1.]]),
 array([[  99.,   73.,   18., ...,   87.,    3.,   14.],
        [   0.,   86.,   65., ...,    0.,   70.,   79.],
        [   0.,    0.,  112., ...,  -65.,   79.,   25.],
        ...,
        [   0.,    0.,    0., ...,  -52.,  205.,   68.],
        [   0.,    0.,    0., ...,    0., -252., -101.],
        [   0.,    0.,    0., ...,    0.,    0.,  -62.]]))

In [49]:

def LU_factorization(A):
    
    def multiplication(M, N):
                                                                                                                                                                                                      
        tuple_mult = list(zip(*N))

        #  matrix multiplication                                                                                                                                                                                     
        return [[sum(el_m * el_n for el_m, el_n in zip(row_m, col_n)) for col_n in tuple_mult] for row_m in M]

    def pivot(M):
        m = len(M)

        # Create an identity matrix                                                                                                                                                                                           
        id_mat = [[float(i ==j) for i in range(m)] for j in range(m)]

        # largest element is placed on diagonal
        
        for j in range(m):
            row = max(range(j, m), key=lambda i: abs(M[i][j]))
            if j != row:
                # Swap the rows                                                                                                                                                                                                                            
                id_mat[j], id_mat[row] = id_mat[row], id_mat[j]

        return id_mat
    
    def lu_decomposition(A):
        
        n = len(A)

        # Create zero matrices for L and U                                                                                                                                                                                                                 
        L = [[0.0] * n for i in range(n)]
        U = [[0.0] * n for i in range(n)]

        # Create the pivot matrix P and the multipled matrix PA                                                                                                                                                                                            
        P = pivot(A)
        PA = multiplication(P, A)

        # Perform the LU Decomposition                                                                                                                                                                                                                     
        for j in range(n):
                                                                                                                                                                                                         
            L[j][j] = 1.0

            #applying formula
            
            for i in range(j+1):
                s1 = sum(U[k][j] * L[i][k] for k in range(i))
                U[i][j] = PA[i][j] - s1

            for i in range(j, n):
                s2 = sum(U[k][j] * L[i][k] for k in range(j))
                L[i][j] = (PA[i][j] - s2) / U[j][j]

        return P, L, U
    
    P, L, U = lu_decomposition(A)
    
    return P,L,U


In [50]:
LU_factorization(A)

([[1.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0],
  [0.0,
   1.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,

In [51]:
A = np.array([ [7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6] ])

b = np.random.randint(low =1,high = 10, size=(4, 1))



In [52]:
# below is the code for GEPP without any library

def GEPP(A, b, pivot = True):
   
    n = len(A)
    if b.size != n:
        raise ValueError("size error", b.size, n)
    # k represents the current pivot row. 
    
    # Elimination
    for k in range(n-1):
        if pivot:
            # Pivot
            max_element = abs(A[k:,k]).argmax() + k
            
            # Swap
            if max_element != k:
                A[[k,max_element]] = A[[max_element, k]]
                b[[k,max_element]] = b[[max_element, k]]
        else:

            pass
        #Eliminate
        for r in range(k+1, n):
            mult = A[r,k]/A[k,k]
            A[r, k:] = A[r, k:] - mult*A[k, k:]
            b[r] = b[r] - mult*b[k]
    # Back Substitution
    x = np.zeros(n)
    for k in range(n-1, -1, -1):
        x[k] = (b[k] - np.dot(A[k,k+1:],x[k+1:]))/A[k,k]
    return np.array(x)



#below is the code for GEPP with library

def GEPP_with_lib( A, b):
    x = np.linalg.solve(np.linalg.inv(A),b)   
    return x

In [53]:
# set size, fix A and keep b random. And check for x using both function and to compare norm is being used
size_of_mat = 100
A = np.random.randint(low =1,high = 100, size=(size_of_mat, size_of_mat))

for i in range(5):
    b = np.random.randint(low =1,high = 100, size=(size_of_mat, 1))
    a_no_lib = (GEPP(A,b))
#     print(a_no_lib)
    a_lib = (GEPP_with_lib(A,b))
#     print(a_lib)
    
    nl = (LA.norm(a_no_lib, np.inf))
    l = (LA.norm(a_lib, np.inf))
    print(nl - l)
    

-109960.81081410902
-251634.18284117625
-276361.99918663956
-274971.2995449387
-252591.72574933778
